require 'json'

PATH = ARGV[0] || "#{File.dirname(__FILE__)}/thrift_metadata"
`mkdir -p #{PATH}`

def convert(file, value)
  if value.is_a? Hash
    file.write("map[string]interface{}{\n")
    value.each do |key, val|
      file.write("\"#{key}\":")
      convert(file, val)
      file.write(",\n")
    end
    file.write("}")
  elsif value.is_a? Array
    file.write("[]interface{}{\n")
    value.each do |val|
      convert(file, val)
      file.write(",\n")
    end
    file.write("}")
  elsif value.is_a? Numeric
    file.write(value.to_f.to_s)
  elsif value.is_a? String
    file.write("#{value.inspect}")
  elsif value == true || value == false
    file.write(value.to_s)
  else
    raise Exception.new("Unknown type: #{value}")
  end
end

JSON_DIR = ARGV[1] || "#{File.dirname(__FILE__)}/gen-json"
thrift_metadata = []
Dir.foreach(JSON_DIR) do |fname|
  if fname.end_with? ".json"
    thrift_metadata << JSON.parse(File.read("#{JSON_DIR}/#{fname}"))
  end
end

file = open("#{PATH}/thrift_metadata.go", "w")
file.write("package thrift_metadata\n\n")
file.write("/**\nAUTOGENERATED CODE - DO NOT MODIFY\n")
file.write("This code was generated using the generated JSON files from the Thrift definitions\n")
file.write("It is used to figure out the exact request when the request is in human readable form\n")
file.write("*/\n\n")

file.write("var THRIFT_METADATA = ")
convert(file, thrift_metadata)
file.close

`go fmt #{PATH}`